export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as Main } from "./Main"
export { default as Nav } from "./Nav"
export { default as BolosMain } from "./BolosMain"
export { default as CarnesMain } from "./CarnesMain"
export { default as MolhosMain } from "./MolhosMain"
export { default as Loading } from "./Loading"
